[general]
log_level = 4

[server]
network_server = "localhost:1700"
application_server = "localhost:8080"

[simulator]
jwt_token = ""
service_profile_id = ""
duration = 60
activation_time = 5

[simulator.device]
count = 100
uplink_interval = 60
f_port = 10
payload = "uplink_packet_1234"
frequency = 868100000
bandwidth = 125
spreading_factor = 12

[simulator.gateway]
min_count = 3
max_count = 5

[simulator.client]
enable_downlink_test = false
downlink_interval = 15
payload = "downlink_packet_1234"
